Repository hmcts/lau-idam-backend, pull requests merged in 2022-10, with the labels that each got.

#244 LAU-531: Update socket timeout to 60 seconds.
  src/main/resources/application.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-244

#245 LAU-539: Add missing audit suppression
  audit.json
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-245

#246 LAU-524 disabling nightly build during weekend
  Jenkinsfile_nightly
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-246
