Repository hmcts/lau-idam-backend, pull requests merged in 2022-05, with the labels that each got.

#143 LAU-367 Bump flyway version
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-143

#146 LAU-367 Log4j upgrade
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-146

#148 LAU-367 Spring dependency upgrade
  build.gradle
  config/pmd/ruleset.xml
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/config/SwaggerConfiguration.java
  src/main/resources/application.properties
  src/smokeTest/resources/application.properties
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-148

#152 LAU-367 other upgrade
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-152

#157 LAU-367 More upgrades
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-157

#168 Revert "Bump versions.junit from 5.7.2 to 5.8.2"
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-168

#167 LAU-396: Up junit5PluginVersion from 0.12 to 0.15
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-167

#173 PCQ-407 Dependency check fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-173

#174 lau-408 dependency check fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-174

#176 LAU-410 Gradle and databind upgrade
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-176
