Repository hmcts/lau-idam-backend, pull requests merged in 2022-04, with the labels that each got.

#121 LAU-366: Dependency check postgresql
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-121

#124 LAU-366: Fix vulnerability.
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-124

#129 LAU-373: Suppress vulnerability with spring-plugin.
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-129

#135 LAU-377: Suppress springfox vulnerabilities
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-135

#137 LAU-387: Update to fix security scan.
  security.sh
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-137
