Repository hmcts/lau-idam-backend, pull requests merged in 2022-08, with the labels that each got.

#204 PCQ-443 Upgrading libraries
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-204

#205 Lau 443
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-205

#211 LAU-443More libraries upgarde
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-211

#214 LAU-443 upgrade libraries
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-214

#220 Lau-482 removing config properties
  src/main/resources/bootstrap.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-220, enable_fortify_scan

#221 Lau-481 Fortify scan fix
  src/main/resources/bootstrap.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-221

#219 LAU-443 More libraries upgrade
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-219

#223 LAU-490: Upgrade postgres library.
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-223

#228 Add backstage configuration file
  catalog-info.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-228

#227 Remove Libraries
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-227
