Repository hmcts/lau-idam-backend, pull requests merged in 2022-12, with the labels that each got.

#280 LAU-570 h2 database suppresion
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-280

#279 LAU-563 Upgrade Terraform version
  infrastructure/.terraform-version
  infrastructure/variables.tf
Labels: ns:lau, prd:lau, keep-helm, rel:lau-idam-backend-pr-279

#284 LAU-572 dependabot configuration change
  .dependabot/config.yml
  .github/dependabot.yml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-284

#286 LAU-575 Suppressing CVE
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-286

#285 LAU-555: Update to resolve workflow deprecated versions.
  .github/workflows/ci.yml
  .github/workflows/swagger.yml
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-285

#288 LAU-577 dependency upgrade
  build.gradle
  charts/lau-idam-backend/Chart.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-288
