Repository hmcts/lau-idam-backend, pull requests merged in 2022-11, with the labels that each got.

#252 LAU-553 dependency check fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-252

#256 LAU-546 Add SonarQube badges and Overview section
  README.md
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-256

#258 LAU-549 Cleanup helm release on success
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-258

#262 LAU-556 upgrading libraries
  build.gradle
  charts/lau-idam-backend/Chart.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-262

#264 LAU-556 upgrading libraries
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-264

#265 LAU-556 upgrading libraries
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-265

#278 LAU-569: Update postgresql
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-278
