Repository hmcts/lau-idam-backend, pull requests merged in 2023-06, with the labels that each got.

#387 Fix security scan
  audit.json
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-387

#382 Lau 641 user deletion get request
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/CommonSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/UserDeletionAuditGetSteps.java
  src/integrationTest/resources/features/get_user_deletion_audit.feature
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/RequestConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/IdamLogonAuditController.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditController.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/DeletionLogGetRequestParams.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/UserDeletionUser.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/insights/AppInsightsEvent.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/UserDeletionGetResponse.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditService.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifier.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifier.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditControllerGetTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditControllerPostTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionRepositoryStartEndTimeTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifierTest.java
Labels: ns:lau, prd:lau, keep-helm, rel:lau-idam-backend-pr-382

#389 Update audit.json for merge conflict
  audit.json
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-389

#393 Lau-673 suppress CVE
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-393

#391 LAU-671 add idam-user-disposer service to authorised services
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/helper/AuthorizationHeaderHelper.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/helper/DatabaseCleaner.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/BaseSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/utils/TestConstants.java
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-391

#400 LAU-681 suppress CVE-2023-35116, seems like not considered as CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-400

#399 Lau 656 get user account disposal functional tests
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/DeletedAccountSearch.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/DeletedAccountsRequest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/BaseSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/DeletedAccountsGetApiSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnGetApiSteps.java
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-399

#401 LAU-661 bump Spring Boot 3.0.8 to 3.1.1
  build.gradle
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditInsertRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/security/SecurityConfiguration.java
  src/main/resources/application.properties
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-401

#402 LAU-688 bump tomcat to address CVE-2023-34981
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-402
