Repository hmcts/lau-idam-backend, pull requests merged in 2023-01, with the labels that each got.

#297 LAU-584 CVE suppression
  Jenkinsfile_CNP
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-297

#300 LAU-586 suppressing CVE
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-300

#301 LAU-587 dependency check fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-301

#307 LAU-583 Add idam login state
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/LogonLog.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnGetApiSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnPostApiSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditGetSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditPostSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/LogonAuditGetHelper.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/LogonAuditPostHelper.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/LoginState.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/IdamLogonAudit.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/LogonLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/LogonLogResponse.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifier.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifier.java
  src/main/resources/db/migration/V006__Schema.sql
  src/main/resources/h2/V001__Schema.sql
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/IdamLogonAuditControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogServiceTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifierTest.java
Labels: ns:lau, prd:lau, keep-helm, rel:lau-idam-backend-pr-307
