Repository hmcts/lau-idam-backend, pull requests merged in 2023-05, with the labels that each got.

#362 LAU-649 bump spring security version to address vulnerability
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-362

#366 LAU-589 spring boot 3 upgrade
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  charts/lau-idam-backend/Chart.yaml
  charts/lau-idam-backend/values.yaml
  config/checkstyle/checkstyle.xml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/LogOnRequestVO.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/LogonLog.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/AbstractSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/CommonSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/SpringBootIntegrationTest.java
  src/integrationTest/resources/features/delete_logon_audit.feature
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/Application.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/authorization/AuthorizationAuthenticator.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/authorization/RestApiPreInvokeDeleteInterceptor.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/authorization/RestApiPreInvokeInterceptor.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/authorization/ServiceAuthorizationAuthenticator.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/config/AppInsightsConfiguration.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/config/AuthServiceConfiguration.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/IdamLogonAuditController.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/IdamLogonAuditDeleteController.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/IdamLogonAudit.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/LogonLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/insights/AppInsights.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/LogonLogGetResponse.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yml
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/authorization/RestApiPreInvokeDeleteInterceptorTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/authorization/RestApiPreInvokeInterceptorTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/config/AppInsightsConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/config/SwaggerGeneratorTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/insights/AppInsightsTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonRepositoryStartEndTimeTest.java
  src/test/resources/application.yaml
Labels: ns:lau, prd:lau, keep-helm, rel:lau-idam-backend-pr-366

#356 Refactor find idam logon query
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditFindLogonRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonRepositoryStartEndTimeTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogServiceTest.java
Labels: ns:lau, prd:lau, keep-helm, rel:lau-idam-backend-pr-356

#367 LAU-654 Security Scan fixed
  audit.json
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-367

#373 LAU-654 Security scan fix
  audit.json
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-373

#374 Update keystore configs.
  build.gradle
  charts/lau-idam-backend/Chart.yaml
  charts/lau-idam-backend/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-374

#368 LAU-634 added user deletion audit model
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/UserDeletionAudit.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/UserDeletionUser.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditInsertRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepository.java
  src/main/resources/db/migration/V008__Schema.sql
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionRepositoryStartEndTimeTest.java
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-368

#375 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-375

#384 Lau-655 security scan fix
  audit.json
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-384

#385 LAU-612 bump gradle version to 8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-385

#376 LAU-640 user deletion audit log post request endpoint
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/DeletedAccount.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/DeletedAccountsRequest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/BaseSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/DeletedAccountsPostApiSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnGetApiSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnPostApiSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/utils/TestConstants.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/UserDeletionAuditPostSteps.java
  src/integrationTest/resources/features/post_user_deletion_audit.feature
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditController.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/UserDeletionAudit.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/DeletionLog.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/UserDeletionUser.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/insights/AppInsightsEvent.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/request/UserDeletionPostRequest.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/UserDeletionPostResponse.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditService.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifier.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifier.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditControllerTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditServiceTest.java
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-376
