Repository hmcts/lau-idam-backend, pull requests merged in 2023-03, with the labels that each got.

#333 Lau-611 dependabot configuration
  .github/dependabot.yml
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-333

#334 LAU-580 remove suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-334

#339 LAU-618 suppressing CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-339

#345 Query performance improvement and remove h2 db
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java
  src/main/resources/db/migration/V007__Schema.sql
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonRepositoryStartEndTimeTest.java
  src/test/resources/application.yaml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-345

#346 Delete h2 folder
  build.gradle
  src/main/resources/h2/V001__Schema.sql
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-346

#347 CVE-2023-20861 fix
  build.gradle
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-347
