Repository hmcts/lau-idam-backend, pull requests merged in 2023-11, with the labels that each got.

#541 LAU-803 increase size for postgres flexible server
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:lau, prd:lau, no-changes, rel:lau-idam-backend-pr-541

#542 LAU-802 remove dependabot
  .github/dependabot.yml
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-542

#568 Enable functional tests
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-568

#563 LAU-817 Get all Deleted User end point
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/AllDeletedAccountsApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/DeletedAccountsGetApiSteps.java
  src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/utils/TestConstants.java
  src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/UserDeletionAuditGetSteps.java
  src/integrationTest/resources/features/get_user_deletion_audit.feature
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditController.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/DeletionLogAllUsersRequestParams.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/insights/AppInsightsEvent.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditService.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifier.java
  src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditControllerGetAllTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditServiceTest.java
Labels: ns:lau, prd:lau, destroy, rel:lau-idam-backend-pr-563, enable_keep_helm

#576 Update audit.json
  audit.json
Labels: ns:lau, prd:lau, rel:lau-idam-backend-pr-576
